---
- name: Initialize Router
  hosts: routers
  connection: network_cli
  gather_facts: no

  vars:
    banner_message: oops, you ran this playbook without reading it first!

  tasks:
  - name: configure {{ inventory_hostname }} hostname
    ios_config:
      lines: hostname {{ inventory_hostname }}

  - name: configure interface Gig2
    ios_config:
      lines:
        - no shutdown
        - description WAN
        - ip address dhcp
      parents: interface GigabitEthernet2

  - name: configure interface Gig1
    ios_config:
      lines:
        - description MGMT
      parents: interface GigabitEthernet1
      
  - name: Setting banner message to "{{ banner_message }}"
    ios_config:
      lines:
        - banner motd % {{ banner_message }} %
        
  - name: add username and password to router
    ios_config:
      lines:
        - username siduser105 privilege 15 secret cisco
...
